[package]
name    = "kappa"
version = "0.0.2-dev"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[dependencies]
anyhow            = "1.0.19"
capnp             = "0.10.1"
crossbeam-channel = "0.3.9"
errno             = "0.2.4"
futures           = "0.3.1"
jemallocator      = "0.3.2"
nixv              = "0.0.1"
num_cpus          = "1.11.1"
libc              = "0.2.65"
log               = "0.4.8"
parking_lot       = "0.9.0"
pcap              = "0.7.0"
regex             = "1.3.1"
rustls            = "0.16.0"
serde_json        = "1.0.41"
signal-hook       = "0.1.11"
time              = "0.1.42"

[dependencies.clap]
version  = "2.33.0"
features = ["yaml"]
default-features = false

[dependencies.env_logger]
version  = "0.7.1"
features = ["humantime"]
default-features = false

[dependencies.pnet]
version  = "0.23.0"
features = ["serde"]

[dependencies.serde]
version  = "1.0.102"
features = ["derive", "rc"]

[dependencies.tokio]
git = "https://github.com/tokio-rs/tokio"
rev = "27e5b410"

[dependencies.tokio-util]
git = "https://github.com/tokio-rs/tokio"
rev = "27e5b410"

[dependencies.tokio-serde]
git      = "https://github.com/wg/tokio-serde"
rev      = "formats"
features = ["json"]

[dependencies.kentik-api]
path = "./kentik-api"

[target.'cfg(target_os = "linux")'.dependencies]
bpf  = "0.1.3"
ebpf = "0.0.4"
nell = "0.2.0"
nixv = "0.0.1"
perf = "0.0.2"

[build-dependencies]
capnpc = "0.10.1"

[profile.release]
lto   = false
debug = true
