[package]
name    = "kentik-api"
version = "0.0.1"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[dependencies]
anyhow            = "1.0.13"
log               = "0.4.8"
rustls            = "0.16.0"
serde_json        = "1.0.41"
webpki-roots      = "0.18.0"

[dependencies.futures-util-preview]
version = "0.3.0-alpha.19"

[dependencies.hyper]
version = "0.13.0-alpha.4"

[dependencies.hyper-rustls]
version = "0.18.0-alpha.2"

[dependencies.http]
version = "0.1.19"

[dependencies.tokio]
version = "0.2.0-alpha.5"

[dependencies.serde]
version  = "1.0.101"
features = ["derive"]
